### ISSUE TITLE
Add user preference to disable/enable bunny-hopping

### ISSUE THREAD

**Issue by infinitephantasm** [Mikusch/deathrun#14]
title

certain platforming-intense maps can be quite annoying to play with this feature active, as accidentally holding space can sometimes send you careening off an edge when normally it wouldn't do so

having it as a preference you can simply toggle would be really nice to have for scenarios like that, or for the rare person who simply doesn't want to use bunnyhops. also just generally a nice QoL thing

**Comment by Mikusch** [comment]
Bunny-hopping is not a part of this plugin.
