### ISSUE TITLE
Anti-AFK and trigger_hurt problem

### ISSUE THREAD

**Issue by saxybois** [Mikusch/deathrun#15]
Hello, there is such a problem that when i using your deathrun plugin anti-AFK doesn't kill, or in some maps trigger_hurt doesn't work correctly and no errors in logs (like Gaben in dr_bank doesn't killing players, but on other deahrun plugins he's does). On other deathrun plugins, trigger_hurt and anti-AFK works and killing players. Also in the code, the only thing I added was to remove any weapons, except for melee. 
What it can be?

**Comment by Mikusch** [comment]
The plugin doesn't do anything that would be able to cause this issue, unless you've modified it to do so. I suggest you check your other plugins for possible culprits, and try unloading Deathrun Neu to see if it's one of your modifications.

**Comment by saxybois** [comment]
> 
> 
> The plugin doesn't do anything that would be able to cause this issue, unless you've modified it to do so. I suggest you check your other plugins for possible culprits, and try unloading Deathrun Neu to see if it's one of your modifications.

Ok, will try it

**Comment by saxybois** [comment]
Well, it was problem with hp reduced damage plugin for VIPs, strange.
