### ISSUE TITLE
Classes with positive speed modifiers can move while frozen during preround time

### ISSUE THREAD

**Issue by jack5github** [Mikusch/deathrun#17]
The amount a class is able to move is directly proportional to how much their speed is being modified. For example, dr_speed_modifier_heavy 70.0 lets a Heavy move roughly 70 HU/s.

**Comment by Mikusch** [comment]
Hi, thanks for the report. This happens because the player speed during preround is actually 1 HU/s, not 0. So it multiplies 1 HU/s x 70 and has this effect.

I'll add a check to not apply speed modifiers during preround time.
