### ISSUE TITLE
Heavy is too slow

### ISSUE THREAD

**Issue by eno26** [Mikusch/deathrun#27]
Our beloved fatman known as the heavy is way too slow in most deathrun maps, forcing him to perform weird maneuvers to jump past
certain traps.
This isn't a specific map issue, because most, if not all maps were designed in mind of every mercenary having the same speed, and that's of course meant to be different in this version of Deathrun, but Heavy is pretty much unusable on 70% of the maps.
I would suggest making him slightly faster, just so he can make these jumps (obviously would have to be disabled whenever the player equips the G.R.U).

**Comment by worMatty** [comment]
If the server operator wants to make that class faster they are free to do so using the provided console variables.
